### ISSUE TITLE
How to use it? No window shown in my computer

### ISSUE THREAD

**Issue by pz0910** [riverrun/cheesemaker#1]

**Comment by pz0910** [comment]
I have built and installed this program.
But when I typed "cheesemaker", there was no responds to this cmd.
Could you please tell me how to use it?

**Comment by riverrun** [comment]
Can you run `cheesemaker` from the terminal and let me know what the output is?

**Comment by pz0910** [comment]
Thanks for replying.
Here are the results in terminal.
![image](https://user-images.githubusercontent.com/31594921/56287323-9c5a0780-614e-11e9-8f07-cfb9766e0f9d.png)
Maybe it is not suitable for windows system?

**Comment by pz0910** [comment]
As you can see, there is no responds for the cmd ‘cheesemaker’

**Comment by riverrun** [comment]
Could you try running the command `cheesemaker` in the Python shell?

**Comment by riverrun** [comment]
Closing this issue, as I am going to archive the repository - due to it being out-of-date.
